### ISSUE TITLE
Django 3 compatibility

### ISSUE THREAD

**Issue by thenewguy** [mback2k/django-celery-model#14]
Need to update for Django 3.  Traceback indicates importing some code that was removed from Django

```
$ /home/vagrant/.tox/py36/bin/python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)

...

    from djcelery_model.models import ModelTaskMeta, TaskMixin
  File "/home/vagrant/.tox/py36/lib/python3.6/site-packages/djcelery_model/models.py", line 12, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'
ERROR: InvocationError for command /home/vagrant/.tox/py36/bin/python manage.py makemigrations (exited with code 1)
```

**Comment by mback2k** [comment]
@thenewguy Thanks, I will try to take a look at your issues and PRs over the holidays.

**Comment by toothstone** [comment]
Hi, is there any hope this will maybe get merged these holidays? :D
