### ISSUE TITLE
Issue with migrations

### ISSUE THREAD

**Issue by kkoci** [mback2k/django-celery-model#22]
Hi, I just installed this module

Followed the tutorial from pypi

However, when I try to run my django instance, it throws me this:

> worker_1    | 
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 288, in send
worker_1    |     response = receiver(signal=self, sender=sender, **named)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/djcelery_model/models.py", line 234, in handle_task_postrun
worker_1    |     queryset.update(state=ModelTaskMetaState.lookup(state))
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 741, in update
worker_1    |     rows = query.get_compiler(self.db).execute_sql(CURSOR)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1462, in execute_sql
worker_1    |     cursor = super().execute_sql(result_type)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
worker_1    |     cursor.execute(sql, params)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
worker_1    |     return super().execute(sql, params)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
worker_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
worker_1    |     return executor(sql, params, many, context)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
worker_1    |     return self.cursor.execute(sql, params)
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
worker_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
worker_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
worker_1    |     return self.cursor.execute(sql, params)
worker_1    | django.db.utils.ProgrammingError: relation "djcelery_model_modeltaskmeta" does not exist
worker_1    | LINE 1: UPDATE "djcelery_model_modeltaskmeta" SET "state" = 4 WHERE ...

Then, by checking out to the branch 'dependabot/pip/django-3.0.7', I found out there are some migrations for Django. (Django 3.x, not south)

This error tells me there is an issue with those

I was expecting it to work out of the box since the tutorial never mentions this, I guess I need to run them?

If so, how? Any idea on this?

Thank You

**Comment by kkoci** [comment]
Nevermind, I ran the migrations for the djcelery_model and it went well

Thanks
